apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    stack: storage
    component: nfs-server-provisioner
spec:
  project: default
  source:
    repoURL: https://github.com/pentago/storage.git
    targetRevision: HEAD
    path: 'nfs-server-provisioner'
    helm:
      valueFiles:
        - values.yaml
  destination:
    namespace: nfs
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
